version: '3'
services:
  shop_portal_db:
    image: 'postgres:latest'
    environment:
      POSTGRES_USER: shoper
      POSTGRES_PASSWORD: shoper@123
      POSTGRES_DB: shopper
      LC_COLLATE: en_US.utf8
      LC_CTYPE: en_US.utf8
      ENCODING: UTF8
      TEMPLATE: template0
    ports:
      - "5432:5432"
    volumes:
      - ./shop-data:/var/lib/postgresql/data